### ISSUE TITLE
Transfer ownership of project

### ISSUE THREAD

**Issue by mgodave** [esl-client/esl-client#16]
Find someone willing to take over this project. I do not work on telephony anymore and am not in a position to maintain this anymore.

**Comment by livem** [comment]
I just pull a request to thisproject.

**Comment by davewo** [comment]
@mgodave I'm interested in taking over the project. What are the next steps for us?

**Comment by mgodave** [comment]
I'm on vacation right now. When I get back to a computer I'll transfer
ownership. Feel free to reach out again if I haven't by Friday.

**Comment by mgodave** [comment]
@davewo Still want it?

**Comment by livem** [comment]
I'm interested in taking over this project. I'm working on VoIP project over 6 years, which based on FreeSWITCH or Asterisk.

**Comment by mgodave** [comment]
@davewo @livem I have transferred ownership to an organization and made you both owners.

**Comment by livem** [comment]
Thanks
