### ISSUE TITLE
Class Not Found

### ISSUE THREAD

**Issue by Tangwego** [esl-client/esl-client#26]
Where are class 'EventFormat' , 'IClientHandlerFactory' and 'IClientHandler'
What's the use of 'InetSocketAddress' ?

**Comment by jamesjieye** [comment]
The code on Maven repository is outdated. If you use that to add the lib, you will get these error. You can download the code and import into your project directly.

**Comment by Tangwego** [comment]
Yes , I got it . Thank you very much!
