### ISSUE TITLE
Support for Chinese

### ISSUE THREAD

**Issue by StoneGH** [esl-client/esl-client#27]
private String readLine(ByteBuf buffer, int maxLineLength) throws TooLongFrameException {
        StringBuilder sb = new StringBuilder(64);
//		while (buffer.isReadable()) {
//			// this read should always succeed
//			byte nextByte = buffer.readByte();
//			if (nextByte == LF) {
//				return sb.toString();
//			} else {
//				// Abort decoding if the decoded line is too large.
//				if (sb.length() >= maxLineLength) {
//					throw new TooLongFrameException(
//						"ESL message line is longer than " + maxLineLength + " bytes.");
//				}
//				sb.append((char) nextByte);
//			}
//		}

        List<Byte> bytes = new ArrayList<>();
        while (buffer.isReadable()) {
            // this read should always succeed
            byte nextByte = buffer.readByte();
            if (nextByte == LF) {
                break;
            } else {
                // Abort decoding if the decoded line is too large.
                if (sb.length() >= maxLineLength) {
                    throw new TooLongFrameException(
                            "ESL message line is longer than " + maxLineLength + " bytes.");
                }
                bytes.add(nextByte);
            }
        }

        try {
            String str = new String(Bytes.toArray(bytes), "UTF-8");
            return str;
        } catch (UnsupportedEncodingException e) {
            e.printStackTrace();
        }
        return sb.toString();
    }
}

**Comment by zhangconan** [comment]
EslFrameDecoder class
```
    private String readLine(ChannelBuffer buffer, int maxLineLength) throws TooLongFrameException, UnsupportedEncodingException {
        byte[] bytes = new byte[maxLineLength];
        int i = 0;
        while (buffer.readable()) {
            byte nextByte = buffer.readByte();
            if (nextByte == LF) {
                return new String(bytes, 0, i, "utf-8");
            } else {
                // Abort decoding if the decoded line is too large.
                if (i >= maxLineLength) {
                    throw new TooLongFrameException(
                            "ESL message line is longer than " + maxLineLength + " bytes.");
                }
                bytes[i++] = nextByte;
            }
        }
        return new String(bytes, 0, i, "utf-8");
    }

**Comment by livem** [comment]
@StoneGH 

支持中文？为什么要支持中文呢？

**Comment by StoneGH** [comment]
@livem 有需要把语音转成中文

**Comment by StoneGH** [comment]
@zhangconan play_and_detect_speech 播放录音并识别  java esl  在什么事件里获取detect_speech_result更好？

**Comment by livem** [comment]
这是 FreeSWITCH 范畴的问题了哈


On 3/29/2019 10:42，Stone<notifications@github.com> wrote：

@zhangconan play_and_detect_speech 播放录音并识别 java esl 在什么事件里获取detect_speech_result更好？

**Comment by StoneGH** [comment]
@livem 在lua里面很好获得， Java 不清楚怎么获得？ 很多事件里面获得detect_speech_result都是空的

**Comment by livem** [comment]
关于 FreeSWITCH 的问题，最好是到 http://bbs.freeswitch.org.cn 或者 https://groups.google.com/forum/#!forum/freeswitch-cn 上面进行咨询哈，上面比较多人可以回答您的问题。


再者，这个问题刚好前两周我也遇到了，我分享一下我的发现：


关于 语音识别，可以在 FreeSWITCH 里面使用这两个 app：
play_and_detect_speech
detect_speech


调试过程中，我发现，只有第二个 app 才触发 DETECTED_SPEECH 事件的。


On 3/29/2019 10:54，Stone<notifications@github.com> wrote：

@livem 在lua里面很好获得， Java 不清楚怎么获得？ 很多事件里面获得detect_speech_result都是空的

**Comment by StoneGH** [comment]
detect_speech这种方式还是很方便，但是不支持打断

**Comment by livem** [comment]
我建议，还是到 FreeSWITCH 论坛上面问问其他人哈


On 3/29/2019 11:11，Stone<notifications@github.com> wrote：

detect_speech这种方式还是很方便，但是不支持打断

**Comment by livem** [comment]
@StoneGH 

有个折衷的解决办法，

1、在 lua 里面使用 play_and_detect_speech  app 进行一边播放录音、一边语音识别；
2、等到有识别结果了，在 lua 脚本里面先获取到 detect_speech_result；
3、在 lua  脚本里面自己触发一个 自定义事件，附带上上述获取到的识别结果；
4、这样 Java esl-client 可以收到这个事件了，也可以得到识别结果了。

**Comment by StoneGH** [comment]
留个微信或QQ 交流下

**Comment by StoneGH** [comment]
@StoneGH 留个微信或QQ交流下

**Comment by StoneGH** [comment]
@livem 混合方式，性能应该有影响，不行就用lua实现了   留个QQ或者微信 多交流交流

**Comment by StoneGH** [comment]
@livem 混合方式，性能应该有影响，不行就用lua实现了 留个QQ或者微信 多交流交流

**Comment by livem** [comment]
这种方案，我想，应该没有什么性能影响的


On 3/29/2019 14:12，Stone<notifications@github.com> wrote：

@livem 混合方式，性能应该有影响，不行就用lua实现了 留个QQ或者微信 多交流交流

**Comment by YounianC** [comment]
> 关于 FreeSWITCH 的问题，最好是到 http://bbs.freeswitch.org.cn 或者 https://groups.google.com/forum/#!forum/freeswitch-cn 上面进行咨询哈，上面比较多人可以回答您的问题。 再者，这个问题刚好前两周我也遇到了，我分享一下我的发现： 关于 语音识别，可以在 FreeSWITCH 里面使用这两个 app： play_and_detect_speech detect_speech 调试过程中，我发现，只有第二个 app 才触发 DETECTED_SPEECH 事件的。 On 3/29/2019 10:54，Stone<notifications@github.com> wrote： @livem 在lua里面很好获得， Java 不清楚怎么获得？ 很多事件里面获得detect_speech_result都是空的 — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

play_and_detect_speech 也可以触发 DETECTED_SPEECH  的，加上：`originate  {fire_asr_events=1}user/8801 wait_for_answer,play_and_detect_speech:'/data/1.wav detect:unimrcp:unimrcpserver-mrcp2 hello',park inline`
